In [10]:
 #Data Analysis libraries
import numpy as np
import pandas as pd

import string
import os


# Data Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("darkgrid")
%matplotlib inline

# NLP Modules
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from wordcloud import WordCloud
from sklearn.feature_extraction.text import CountVectorizer


# SkLearn for ML Model
from sklearn.model_selection import train_test_split 
from sklearn import metrics

In [11]:
df_train = pd.read_csv("train_final_2.csv")

In [12]:
df_train

sim_score  lex_val_score  lex_div_score  sentiment_score  \
0         0.000000       0.275362       0.357488           0.9869   
1         0.457450       0.217791       0.306748           0.9963   
2         0.536652       0.196491       0.298246           0.9945   
3         0.392120       0.264706       0.362745           0.9944   
4         0.502954       0.219880       0.313253           0.9968   
...            ...            ...            ...              ...   
3599994   0.309465       0.285714       0.343915           0.9794   
3599995   0.567870       0.232057       0.294258           0.7105   
3599996   0.585350       0.234987       0.300261           0.9817   
3599997   0.468018       0.266667       0.369231           0.8689   
3599998   0.296777       0.209375       0.290625           0.9925   

         Review_Subjectivity  text_count_score  Label  
0                   0.530252               NaN      2  
1                   0.525163               NaN      2  
2                   0.438095               NaN      2  
3                   0.520317               NaN      2  
4                   0.480101               NaN      2  
...                      ...               ...    ...  
3599994             0.491263               NaN      1  
3599995             0.544145               NaN      1  
3599996             0.570259               NaN      1  
3599997             0.531717               NaN      1  
3599998             0.233333               NaN      2  

[3599999 rows x 7 columns]

In [13]:
df_train.drop(['text_count_score'],axis = 1,inplace=True)

In [14]:
df_train

sim_score  lex_val_score  lex_div_score  sentiment_score  \
0         0.000000       0.275362       0.357488           0.9869   
1         0.457450       0.217791       0.306748           0.9963   
2         0.536652       0.196491       0.298246           0.9945   
3         0.392120       0.264706       0.362745           0.9944   
4         0.502954       0.219880       0.313253           0.9968   
...            ...            ...            ...              ...   
3599994   0.309465       0.285714       0.343915           0.9794   
3599995   0.567870       0.232057       0.294258           0.7105   
3599996   0.585350       0.234987       0.300261           0.9817   
3599997   0.468018       0.266667       0.369231           0.8689   
3599998   0.296777       0.209375       0.290625           0.9925   

         Review_Subjectivity  Label  
0                   0.530252      2  
1                   0.525163      2  
2                   0.438095      2  
3                   0.520317      2  
4                   0.480101      2  
...                      ...    ...  
3599994             0.491263      1  
3599995             0.544145      1  
3599996             0.570259      1  
3599997             0.531717      1  
3599998             0.233333      2  

[3599999 rows x 6 columns]

In [15]:
df_test = pd.read_csv("test_final_2.csv")

In [16]:
df_test

sim_score  lex_val_score  lex_div_score  sentiment_score  \
0        0.000000       0.481928       0.614458           0.8770   
1        0.316884       0.597015       0.746269           0.6597   
2        0.223309       0.444444       0.755556           0.7845   
3        0.270464       0.576923       0.807692           0.8388   
4        0.196296       0.517647       0.705882          -0.3506   
...           ...            ...            ...              ...   
399994   0.443192       0.397790       0.524862           0.5932   
399995   0.313604       0.525547       0.620438          -0.5144   
399996   0.436171       0.485294       0.617647           0.6911   
399997   0.274593       0.490196       0.725490           0.9217   
399998   0.517006       0.470238       0.625000           0.9280   

        Review_Subjectivity  text_count_score  Label  
0                  0.538542               NaN      2  
1                  0.666667               NaN      1  
2                  0.500000               NaN      2  
3                  0.497470               NaN      2  
4                  0.433333               NaN      1  
...                     ...               ...    ...  
399994             0.580257               NaN      1  
399995             0.480556               NaN      1  
399996             0.634028               NaN      1  
399997             0.538095               NaN      2  
399998             0.329167               NaN      1  

[399999 rows x 7 columns]

In [17]:
df_test.drop(['text_count_score'],axis = 1,inplace=True)

In [18]:
df_test

sim_score  lex_val_score  lex_div_score  sentiment_score  \
0        0.000000       0.481928       0.614458           0.8770   
1        0.316884       0.597015       0.746269           0.6597   
2        0.223309       0.444444       0.755556           0.7845   
3        0.270464       0.576923       0.807692           0.8388   
4        0.196296       0.517647       0.705882          -0.3506   
...           ...            ...            ...              ...   
399994   0.443192       0.397790       0.524862           0.5932   
399995   0.313604       0.525547       0.620438          -0.5144   
399996   0.436171       0.485294       0.617647           0.6911   
399997   0.274593       0.490196       0.725490           0.9217   
399998   0.517006       0.470238       0.625000           0.9280   

        Review_Subjectivity  Label  
0                  0.538542      2  
1                  0.666667      1  
2                  0.500000      2  
3                  0.497470      2  
4                  0.433333      1  
...                     ...    ...  
399994             0.580257      1  
399995             0.480556      1  
399996             0.634028      1  
399997             0.538095      2  
399998             0.329167      1  

[399999 rows x 6 columns]

In [19]:
X = df_train.iloc[:, :-1].values
y = df_train.iloc[:, -1].values

In [20]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [21]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 100) 
clf.fit(X_train, y_train)

RandomForestClassifier()

In [22]:
y_pred_train = clf.predict(X_train)


In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_pred_train,y_train))
print(accuracy_score(y_pred_train,y_train))

[[1439341      24]
 [     38 1440596]]
0.9999784722147473


In [24]:
X_test = df_train.iloc[:, :-1].values
y_test = df_train.iloc[:, -1].values

In [27]:
X_train

array([[ 0.13997084,  0.33333333,  0.43010753, -0.7954    ,  0.67142857],
       [ 0.2006309 ,  0.2994012 ,  0.38922156,  0.9695    ,  0.31666667],
       [ 0.45516294,  0.29411765,  0.38235294,  0.9594    ,  0.4625    ],
       ...,
       [ 0.25488191,  0.24347826,  0.35217391,  0.9858    ,  0.40789474],
       [ 0.40276028,  0.296     ,  0.384     ,  0.9467    ,  0.63      ],
       [ 0.28915747,  0.34246575,  0.42465753,  0.9571    ,  0.17222222]])

In [28]:
df_train

sim_score  lex_val_score  lex_div_score  sentiment_score  \
0         0.000000       0.275362       0.357488           0.9869   
1         0.457450       0.217791       0.306748           0.9963   
2         0.536652       0.196491       0.298246           0.9945   
3         0.392120       0.264706       0.362745           0.9944   
4         0.502954       0.219880       0.313253           0.9968   
...            ...            ...            ...              ...   
3599994   0.309465       0.285714       0.343915           0.9794   
3599995   0.567870       0.232057       0.294258           0.7105   
3599996   0.585350       0.234987       0.300261           0.9817   
3599997   0.468018       0.266667       0.369231           0.8689   
3599998   0.296777       0.209375       0.290625           0.9925   

         Review_Subjectivity  Label  
0                   0.530252      2  
1                   0.525163      2  
2                   0.438095      2  
3                   0.520317      2  
4                   0.480101      2  
...                      ...    ...  
3599994             0.491263      1  
3599995             0.544145      1  
3599996             0.570259      1  
3599997             0.531717      1  
3599998             0.233333      2  

[3599999 rows x 6 columns]

In [26]:
y_pred_test = clf.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_pred_test,y_test))
print(accuracy_score(y_pred_test,y_test))

[[1710853   88480]
 [  89147 1711519]]
0.9506591529608758
